### ISSUE TITLE
purefa_syslog requires name, but purefa_info does not provide information

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#784]
**Environment**

- Ansible version: core 2.15.8
- FlashArray Collection version: 1.36.0
- Purity version: 6.7.3
- FlashArray module causing the failure: purefa_syslog and purefa_info

**Description**
When trying to delete a syslog configuration using purefa_syslog, the "name" parameter is required.
However, purefa_info only returns the syslog information as a URI, for example:
```
"syslog": [
    "UDP://10.229.113.127"
]
```

I think one of the following changes would resolve the issue:
- Make name optional in purefa_syslog for deletion (or modification) operations.
- Make purefa_info return the name of each syslog entry in addition to the URI.

**Additional Question**
Could you please let me know if there is a plan or an estimated timeline for completing purefa_info’s full REST API v2 support?

Thank you,

**Comment by ryuyamag** [comment]
This new v2 version seems to require FlashArray REST API 2.38 or higher, is that correct?

If so, my customers would prefer that purefa_syslog be fixed.

**Comment by sdodsley** [comment]
There is no reason for 2.38 to be required. 
Can you explain why you think this is the case?
Do you see any error messaes from `purefa_info` when running on your Purity//FA 6.7.3 array?

**Comment by ryuyamag** [comment]
The new v2 version still gives the same error. The old purefa_info works fine. 
Is there something wrong with my assumptions?

[purefa_infov2_all_20250827.log](https://github.com/user-attachments/files/21998501/purefa_infov2_all_20250827.log)

**Comment by ryuyamag** [comment]
@sdodsley 
Thank you for updating the source.
I can see a difference from last time, and it looks like the processing has progressed further.

```
  File "/usr/local/lib/python3.9/site-packages/pypureclient/flasharray/FA_2_36/models/certificate.py", line 100, in __getattribute__
    raise AttributeError
AttributeError
```

[purefa_infov2_all_20250830.log](https://github.com/user-attachments/files/22049197/purefa_infov2_all_20250830.log)

**Comment by sdodsley** [comment]
Yes - it proegreesed further - the certifcate issue is now fixed.

**Comment by ryuyamag** [comment]
Thanks for fixing. However, it still throws an error around the certificate.

[purefa_infov2_all_20250830b.log](https://github.com/user-attachments/files/22049777/purefa_infov2_all_20250830b.log)

**Comment by ryuyamag** [comment]
Great! It seems fine now.
I’ll check the results and get back to you, but it may take a few days.

**Comment by ryuyamag** [comment]
@sdodsley 
Sorry for the late reply.
When comparing the output, I found almost no issues, but I did notice some differences.
I will contact you directly.

**Comment by sdodsley** [comment]
@ryuyamag thnak you for that. I believe I have now resolved those differences. Please check.

**Comment by ryuyamag** [comment]
@sdodsley 
I found an error. Could you please take a look?

[purefa_infov2_all_20250908.log](https://github.com/user-attachments/files/22199917/purefa_infov2_all_20250908.log)

**Comment by sdodsley** [comment]
That was a typo - fixed
